### PR TITLE
Feature/profile

### PR DESCRIPTION
**Pull request by pawalt**
This PR:
- Creates a profile page

### CODE REVIEW

**Comment by benleim** [comment]
LGTM

**Comment by ArmaanT** [comment]
I added the ability to follow other users. We probably want to create a check to see if the current page belongs to the logged in user, don't show the follow button. Other than that, it looks good to me.

**Review by ArmaanT — APPROVED** [review]

**Comment by pawalt** [comment]
I added a hook for unfollowing. Please review and merge. Everything else LGTM

**Comment by pawalt** [comment]
Great job

**Pull request merged**
